import type { Metadata } from "next";
import { Catamaran, Shrikhand } from "next/font/google";
import "./globals.css";
import React from "react";

const shrikhand = Shrikhand({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-shrikhand",
});

const catamaran = Catamaran({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-catamaran ",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${shrikhand.variable} ${catamaran.variable}`}>
        {children}
      </body>
    </html>
  );
}
